### ISSUE TITLE
你好？看了你的demo,可以让.framework支持ios7吗

### ISSUE THREAD

**Issue by topjx** [crossle/AppRTCMobile#1]
你好？看了你的demo,可以让.framework支持ios7吗

**Comment by crossle** [comment]
无法支持 iOS 7， iOS 7 硬编码都不支持。

**Comment by topjx** [comment]
就是说ios7不支持自己生成的.framework吗？但是我看网上好多第三方提供的也是.framework，也支持了ios7啊

**Comment by crossle** [comment]
反正 WebRTC 本身是不支持 iOS 7，其他的第三方的可能自己处理的，为啥还要支持 iOS 7？WebRTC 支持 8.0+

**Comment by topjx** [comment]
你项目里的.framework是最新版的webrtc吗

**Comment by crossle** [comment]
是的

**Comment by topjx** [comment]
今天发现一个问题，两台iPhone，一台连wifi,另外一台连3G或4G,两台就不能通信了，必须两台都是WiFi才可以通信，只要其中有一台连的不是WiFi就不能通信，WiFi可以是异地的，比如一个北京、一个上海，你遇到这种情况吗？

**Comment by crossle** [comment]
没有，感觉应该是服务端穿透的问题

**Comment by topjx** [comment]
不好意思啊，还得问你问题，怎么设置demo的扬声器和听筒模式切换啊？

**Comment by crossle** [comment]
AppRTCAudioManager.java

**Comment by topjx** [comment]
这个是object-c的demo啊，没有Java的类

**Comment by crossle** [comment]
哦， 搞错了， RTCAudioSession.h

**Comment by topjx** [comment]
这个里面我看了，设置了没作用

**Comment by crossle** [comment]
你怎么设置的？

**Comment by topjx** [comment]
- (void)configureAudioSession {
  RTCAudioSessionConfiguration *configuration =
      [[RTCAudioSessionConfiguration alloc] init];
//    configuration.category = AVAudioSessionCategoryAmbient;
  configuration.category = AVAudioSessionCategoryPlayAndRecord;
  configuration.categoryOptions = AVAudioSessionCategoryOptionDuckOthers;
  configuration.mode = AVAudioSessionModeDefault;

  RTCAudioSession *session = [RTCAudioSession sharedInstance];
  [session.session setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];

**Comment by topjx** [comment]
可以加你QQ吗？1713521474

**Comment by topjx** [comment]
搞错了，进误区了，已经解决了
