### ISSUE TITLE
WebRTC update

### ISSUE THREAD

**Issue by LorenzoMcMaster** [crossle/AppRTCMobile#5]
Hi, It's been 8 months since last update. I would be nice to have an updated version of the project again since a lot of improvement has come to webRTC. Maybe an integration using cocoapods would make updates easier.

**Comment by crossle** [comment]
Yes

**Comment by crossle** [comment]
Welcome to PR

**Comment by crossle** [comment]
https://github.com/crossle/AppRTCMobile/tree/latest-wip
Fixed

**Comment by crossle** [comment]
Merged

**Comment by LorenzoMcMaster** [comment]
Pods integration seams to have an issue. Get this error when building (after cmd pod install)

ld: library not found for -lPods-AppRTCMobile

**Comment by crossle** [comment]
I use cocoapods 1.5.3, it's work fine

**Comment by LorenzoMcMaster** [comment]
Sorry,

I've made the classic mistake, opened the .xcodeproj instead of .xcworkspace

now everything is fine.

Thanks for this great project.
