### ISSUE TITLE
remoteView show

### ISSUE THREAD

**Issue by LongTeng123** [crossle/AppRTCMobile#7]
Hello, The author:

     how can i show remoteView in screen?

    Thank you if you have time.

**Comment by crossle** [comment]
What's wrong? two devices in the same room, it will work.

**Comment by LongTeng123** [comment]
It is connect,bug only see the location video in screen , how to see the remote video? remote is not show  default.

**Comment by sunilju** [comment]
Remote video is not showing in app. Anyone have idea about it.
Please help me.

Thanks in advance.

**Comment by phucdanghuu** [comment]
I got the same issue, could not see remote vide

**Comment by phucdanghuu** [comment]
@LongTeng123 @sunilju seems like it's the issue on iOS 13, the remote video can show on iOS 12

**Comment by sunilju** [comment]
> @LongTeng123 @sunilju seems like it's the issue on iOS 13, the remote video can show on iOS 12

Yes, Till iOS 12, Video is working fine.
iOS 13 and later , Not working.

How can i solve this? Any idea or you have any solution ?
Please let me know?

**Comment by crossle** [comment]
Should sync to lastest version https://webrtc.googlesource.com/src/+/refs/heads/master/examples/objc/AppRTCMobile/

**Comment by sunilju** [comment]
> Should sync to lastest version https://webrtc.googlesource.com/src/+/refs/heads/master/examples/objc/AppRTCMobile/

@crossle , Let me know the process please .
I tried but not able to do that.

**Comment by phucdanghuu** [comment]
@sunilju just resolved this issue.
1. You have to download new AppRTCMobile folder from the link above, and then copy all files and replace them on current source code 
2. Update GoogleWebRTC pod to 1.1.29400

**Comment by crossle** [comment]
@phucdanghuu  Welcome PR

**Comment by phucdanghuu** [comment]
@crossle here we go https://github.com/crossle/AppRTCMobile/pull/8
